name: LunarLite
version: 0.0.1
api: 3.0.0
author: Blackjack200
main: blackjack200\lunarlite\LunarLite

permissions:
  lunar:
    children:
      lunar.list:
        description: List Lunar Anticheat Detections
        default: op